#!/bin/sh
#
# install.sh — make Spotify's window freely resizable.
#
# What it does, in order:
#   1. locates Spotify and refuses to touch a Mac App Store build
#   2. installs the injected library to ~/.spotify-resizer/
#   3. backs up Spotify's Info.plist
#   4. drops a small launch shim next to the real Spotify binary
#   5. repoints CFBundleExecutable at the shim
#
# The real Spotify binary is never modified. Re-running this after a Spotify
# update is safe and is the intended way to re-apply the fix.
#
# Usage:  sh scripts/install.sh [path/to/Spotify.app]

set -eu

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
LIB_SRC="$REPO_ROOT/dist/libnomin.dylib"
INSTALL_DIR="$HOME/.spotify-resizer"
LIB_DST="$INSTALL_DIR/libnomin.dylib"
SHIM_NAME="SpotifyLauncher"
PLIST_BACKUP="$INSTALL_DIR/Info.plist.orig"

SPOTIFY_APP="${1:-/Applications/Spotify.app}"
PLIST="$SPOTIFY_APP/Contents/Info.plist"
MACOS_DIR="$SPOTIFY_APP/Contents/MacOS"
REAL_BIN_NAME="Spotify"
SHIM="$MACOS_DIR/$SHIM_NAME"

say()  { printf '%s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- sanity checks

[ "$(uname -s)" = "Darwin" ] || fail "this only works on macOS"

[ -d "$SPOTIFY_APP" ] || fail "Spotify not found at $SPOTIFY_APP
Install it from https://www.spotify.com/download, or pass the path:
  sh scripts/install.sh /path/to/Spotify.app"

if [ -d "$SPOTIFY_APP/Contents/_MASReceipt" ]; then
	fail "this is a Mac App Store build of Spotify.
Spicetify and this tool cannot patch MAS builds. Reinstall Spotify from
https://www.spotify.com/download and run this again."
fi

[ -f "$PLIST" ] || fail "no Info.plist at $PLIST"
[ -f "$MACOS_DIR/$REAL_BIN_NAME" ] || fail "no $REAL_BIN_NAME binary in $MACOS_DIR"

if [ ! -f "$LIB_SRC" ]; then
	say "dist/libnomin.dylib not found — building it first."
	sh "$REPO_ROOT/scripts/build.sh" || fail "build failed"
fi

# ------------------------------------------------------- already-installed?

current_exec=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$PLIST" 2>/dev/null || echo "")
if [ "$current_exec" = "$SHIM_NAME" ]; then
	say "Already installed (CFBundleExecutable is $SHIM_NAME). Refreshing the library."
else
	say "CFBundleExecutable is '$current_exec' — proceeding."
fi

# ---------------------------------------------------------------- warn if open

if pgrep -f "^$SPOTIFY_APP/Contents/MacOS/$REAL_BIN_NAME( |\$)" >/dev/null 2>&1; then
	say ""
	say "NOTE: Spotify is running. Quit it and reopen before the change takes effect."
	say "      osascript -e 'quit app \"Spotify\"'"
	say ""
fi

# --------------------------------------------------------- install the library

mkdir -p "$INSTALL_DIR"
cp "$LIB_SRC" "$LIB_DST"
chmod 644 "$LIB_DST"

if command -v codesign >/dev/null 2>&1; then
	codesign --force --sign - "$LIB_DST" >/dev/null 2>&1 || true
fi

# macOS quarantines anything downloaded. A quarantined dylib can be refused by
# dyld, which would silently produce a normal, unresizable Spotify.
xattr -d com.apple.quarantine "$LIB_DST" 2>/dev/null || true

say "installed library: $LIB_DST"

# ------------------------------------------------------------- back up the plist

# Only ever capture a PRISTINE plist. If we are re-installing over an existing
# patch, CFBundleExecutable already says SpotifyLauncher — backing that up would
# make uninstall "restore" the patch.
if [ -f "$PLIST_BACKUP" ]; then
	say "plist backup kept: $PLIST_BACKUP (already existed)"
elif [ "$current_exec" = "$REAL_BIN_NAME" ]; then
	cp "$PLIST" "$PLIST_BACKUP"
	say "backed up plist  : $PLIST_BACKUP"
else
	say "WARNING: Info.plist is already modified (CFBundleExecutable = '$current_exec')"
	say "         and no pristine backup exists. Uninstall will set the key back"
	say "         in place rather than restoring a byte-exact file."
fi

# ------------------------------------------------------------------- the shim

# Written with a quoted heredoc so nothing here is expanded at install time.
cat > "$SHIM" <<SHIM_EOF
#!/bin/sh
#
# $SHIM_NAME — generated by spotify-resizer. Do not edit.
#
# Loads the window-minimum-size helper and hands over to the real Spotify
# binary, which sits untouched next to this file as "$REAL_BIN_NAME".
# Remove this file and set CFBundleExecutable back to "$REAL_BIN_NAME" to undo,
# or just run scripts/uninstall.sh.

set -u

LIB="$LIB_DST"
REAL="\$(cd "\$(dirname "\$0")" && pwd)/$REAL_BIN_NAME"

# If the library is missing, still start Spotify. A missing file must never
# leave the user with an app that will not open.
if [ -f "\$LIB" ]; then
	DYLD_INSERT_LIBRARIES="\$LIB"
	export DYLD_INSERT_LIBRARIES
fi

exec "\$REAL" "\$@"
SHIM_EOF

chmod +x "$SHIM"
say "installed shim   : $SHIM"

# ---------------------------------------------------------- repoint the bundle

/usr/libexec/PlistBuddy -c "Set :CFBundleExecutable $SHIM_NAME" "$PLIST"
say "CFBundleExecutable -> $SHIM_NAME"

# LaunchServices caches the bundle metadata. Without this it keeps serving the
# old plist and Spotify launches without the shim.
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
if [ -x "$LSREGISTER" ]; then
	"$LSREGISTER" -f "$SPOTIFY_APP" || true
	say "re-registered with LaunchServices"
fi

# ---------------------------------------------------------------------- done

say ""
say "Done. Restart Spotify:"
say "  osascript -e 'quit app \"Spotify\"' && sleep 2 && open -a Spotify"
say ""
say "Verify the library loaded:"
say "  lsof -p \$(pgrep -f '^$SPOTIFY_APP/Contents/MacOS/$REAL_BIN_NAME( |\$)' | head -1) | grep libnomin"
say ""
say "Then drag the window edge — it will now go below 800px."
say "Note: Spotify updates replace the bundle and undo this. Re-run install.sh after updating."
